spring:  
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      # Este archivo contiene la configuración necesaria para 
      # establecer un microservicio como servidor eureka
      # además de esto se tiene que incluir la dependencia
      #eureka server y la anotación @EnableEurekaServer en la clase main
